name: WakaTime Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "░▒▓█"
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: false
          SHOW_TOTAL: false
          STOP_AT_OTHER: true
